### ISSUE TITLE
The dataset is invalid. Can you provide it again

### ISSUE THREAD

**Issue by Shine-Thomas** [shkim960520/YOLO-v1-for-studying#1]
The dataset is invalid. Can you provide it again

**Comment by sangnekim** [comment]
Hello
Thanks for visiting my repo.
Actually, I am not the owner of the dataset page. So, I can’t provide it to you directly. 
 But I think you can easily download the dataset(PASCAL VOC2007) because it is open data. 
 
Good luck!

**Comment by sangnekim** [comment]
Hello @Shine-Thomas .
Can I close this issue?

Thanks.

**Comment by Shine-Thomas** [comment]
yes，thanks a lot!
